name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.12'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock
        python-version: ${{ matrix.python-version }}
    - run: uv sync --all-extras --dev
    - run: uv run task test:ci
    - uses: qltysh/qlty-action/coverage@325e718842513d9e19baf91280cab9bc6db6e17b
      with:
        coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: ${{github.workspace}}/cov.xml
